// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team1701.robot.commands;

import org.usfirst.frc.team1701.robot.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class Calibrate extends Command {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public Calibrate() {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	}

	long time;
	boolean finished = false;
	// Called just before this Command runs the first time
	protected void initialize() {
		time = System.currentTimeMillis();
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
//		if (System.currentTimeMillis() - time < 1000) {
//			RobotMap.drivetrainLeftDriveMotor2.set(1);
//			RobotMap.drivetrainLeftDriveMotor1.set(1);
//			RobotMap.drivetrainRightDriveMotor2.set(1);
//			RobotMap.drivetrainRightDriveMotor1.set(1);
//		} else if (System.currentTimeMillis() - time < 2000) {
//			RobotMap.drivetrainLeftDriveMotor2.set(-1);
//			RobotMap.drivetrainLeftDriveMotor1.set(-1);
//			RobotMap.drivetrainRightDriveMotor2.set(1);
//			RobotMap.drivetrainRightDriveMotor1.set(1);
//		} else{
//			RobotMap.drivetrainLeftDriveMotor2.set(0);
//			RobotMap.drivetrainLeftDriveMotor1.set(0);
//			RobotMap.drivetrainRightDriveMotor2.set(0);
//			RobotMap.drivetrainRightDriveMotor1.set(0);
//			finished = true;
//		}

	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return finished;
	}

	// Called once after isFinished returns true
	protected void end() {
		finished = false;
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
	}
}
